# Generated by Django 3.0.5 on 2020-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='tag',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
