# Generated by Django 3.0.5 on 2020-04-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='maxPrice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='option',
            name='resolveprice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='minPrice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
