# Generated by Django 3.0.5 on 2020-04-18 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_auto_20200418_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 23, 32, 43, 36450)),
            preserve_default=False,
        ),
    ]
