# Generated by Django 3.0.5 on 2020-04-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_market_creationdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-creationdate']},
        ),
    ]
