# Generated by Django 3.0.5 on 2020-04-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20200418_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={},
        ),
    ]
