# Generated by Django 3.0.5 on 2020-04-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_auto_20200418_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='curated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
