# Generated by Django 3.0.5 on 2020-04-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_auto_20200419_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='rules',
            field=models.TextField(blank=True),
        ),
    ]
