# Generated by Django 3.0.5 on 2020-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_auto_20200419_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='tag',
            field=models.SlugField(blank=True),
        ),
    ]
